# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         sys-MON-Lite
version:      0.02
version_from: lib/sys/MON/Lite.pm
installdirs:  site
requires:
    Class::MethodMaker:            0
    Config::Std:                   0
    Data::GUID:                    0
    DBM::Deep:                     0
    Email::Simple:                 0
    Log::Dispatch::Syslog:         0
    Log::Log4perl:                 0
    Mail::POP3Client:              0
    Module::Pluggable:             0
    Net::IMAP::Simple:             0
    Test::More:                    0
    WWW::Mechanize:                0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
